sonar.projectKey=eduai_auth
sonar.projectName=EduAI Auth
sonar.projectVersion=1.0

# Path to source directories
sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/node_modules/**,*.db,*.json,*.txt,*.md,tests/**

# Path to test directories
sonar.tests=tests

# Python specifics
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
