import os
import logging
import asyncio
from fastapi import FastAPI, Depends, HTTPException, status
from fastapi.responses import RedirectResponse
from fastapi.security import OAuth2PasswordRequestForm
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
from dotenv import load_dotenv
from playwright.async_api import async_playwright

load_dotenv()
logger = logging.getLogger(__name__)

from . import models, schemas, auth
from .database import engine, Base, get_db
from typing import List, Optional
import io
from fastapi.responses import StreamingResponse
from jinja2 import Template

# create DB tables
Base.metadata.create_all(bind=engine)

app = FastAPI(title="Auth Microservice")

# Enable CORS for frontend requests
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Change to specific origins in production: ["https://tu-dominio.com"]
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/", include_in_schema=False)
def root():
    """Root route: redirect to documentation (avoids 404 for GET /)."""
    return RedirectResponse(url="/docs")


@app.post("/register", response_model=schemas.UserOut)
def register(user_in: schemas.UserCreate, db: Session = Depends(get_db)):
    existing = auth.get_user_by_email(db, user_in.email)
    if existing:
        raise HTTPException(status_code=400, detail="Email already registered")
    hashed = auth.get_password_hash(user_in.password)
    user = models.User(email=user_in.email, hashed_password=hashed, full_name=user_in.full_name, provider="email")
    db.add(user)
    db.commit()
    db.refresh(user)
    return user


@app.post("/login", response_model=schemas.Token)
def login(form_data: OAuth2PasswordRequestForm = Depends(), db: Session = Depends(get_db)):
    user = auth.authenticate_user(db, form_data.username, form_data.password)
    if not user:
        raise HTTPException(status_code=401, detail="Incorrect email or password")
    access_token = auth.create_access_token({"sub": user.email})
    return {"access_token": access_token, "token_type": "bearer"}


@app.post("/google-login", response_model=schemas.Token)
def google_login(payload: schemas.GoogleLogin, db: Session = Depends(get_db)):
    # Client should send an id_token obtained from Google Sign-In
    info = auth.verify_google_token(payload.id_token, audience=os.getenv("GOOGLE_CLIENT_ID"))
    email = info.get("email")
    if not email:
        raise HTTPException(status_code=400, detail="Google token has no email")
    user = auth.get_user_by_email(db, email)
    if not user:
        # Create user with provider 'google'
        user = models.User(email=email, full_name=info.get("name"), provider="google")
        db.add(user)
        db.commit()
        db.refresh(user)
    access_token = auth.create_access_token({"sub": user.email})
    return {"access_token": access_token, "token_type": "bearer"}


@app.get("/me", response_model=schemas.UserOut)
def read_me(current_user: models.User = Depends(auth.get_current_user)):
    return current_user


@app.post("/save-session", response_model=schemas.SessionOut)
def save_session(payload: schemas.SessionCreate, db: Session = Depends(get_db)):
    """Save a session payload generated by the backend or frontend for a user."""
    sess = models.UserSession(user_id=payload.user_id, session_data=payload.session_data)
    db.add(sess)
    db.commit()
    db.refresh(sess)
    return sess


@app.get("/sessions", response_model=List[schemas.SessionOut])
def get_sessions(user_id: Optional[str] = None, db: Session = Depends(get_db)):
    """List sessions. If user_id is provided, filter by that user_id."""
    query = db.query(models.UserSession)
    if user_id:
        query = query.filter(models.UserSession.user_id == user_id)
    results = query.order_by(models.UserSession.created_at.desc()).all()
    return results



@app.get("/sessions/{session_id}/pdf")
def session_pdf(session_id: int, db: Session = Depends(get_db)):
    """Generate a professional PDF for a saved session using WeasyPrint.

    Returns a PDF binary with Content-Type application/pdf.
    """
    sess = db.query(models.UserSession).filter(models.UserSession.id == session_id).first()
    if not sess:
        raise HTTPException(status_code=404, detail="Session not found")

    # Professional HTML template with elegant styling (uses standard fonts for better compatibility)
    html_template = Template(r"""
    <!doctype html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body {
                font-family: 'Courier New', Courier, monospace, sans-serif;
                font-size: 11pt;
                line-height: 1.6;
                color: #2c3e50;
                background: white;
                padding: 40px;
            }
            .header {
                border-bottom: 3px solid #2c7fb8;
                padding-bottom: 20px;
                margin-bottom: 30px;
            }
            .header h1 {
                font-size: 24pt;
                color: #1a4d7a;
                margin-bottom: 10px;
            }
            .header-meta {
                display: flex;
                gap: 30px;
                font-size: 10pt;
                color: #555;
            }
            .meta-item {
                flex: 1;
            }
            .meta-item strong {
                color: #2c7fb8;
                display: block;
                margin-bottom: 4px;
            }
            .section {
                margin-bottom: 25px;
                page-break-inside: avoid;
            }
            .section h2 {
                font-size: 14pt;
                color: #1a4d7a;
                border-left: 4px solid #2c7fb8;
                padding-left: 12px;
                margin-bottom: 12px;
                font-weight: bold;
            }
            .section h3 {
                font-size: 12pt;
                color: #2c7fb8;
                margin-top: 12px;
                margin-bottom: 8px;
                font-weight: bold;
            }
            .content {
                background: #f8f9fa;
                padding: 12px;
                border-left: 3px solid #d0e8f2;
                font-size: 10pt;
                line-height: 1.5;
                white-space: pre-wrap;
                word-wrap: break-word;
            }
            .content-clean {
                background: white;
                padding: 8px 0;
            }
            ul {
                margin-left: 20px;
                margin-top: 8px;
            }
            li {
                margin-bottom: 6px;
                line-height: 1.4;
            }
            .info-box {
                background: #ecf0f1;
                border: 1px solid #bdc3c7;
                padding: 10px 12px;
                border-radius: 4px;
                font-size: 10pt;
                margin-bottom: 10px;
            }
            .info-box strong {
                color: #1a4d7a;
            }
            .footer {
                margin-top: 50px;
                padding-top: 15px;
                border-top: 1px solid #bdc3c7;
                font-size: 9pt;
                color: #7f8c8d;
                text-align: center;
            }
            .divider {
                height: 1px;
                background: #ecf0f1;
                margin: 20px 0;
            }
            table {
                width: 100%;
                border-collapse: collapse;
                margin-top: 10px;
            }
            th, td {
                border: 1px solid #bdc3c7;
                padding: 8px;
                text-align: left;
            }
            th {
                background: #2c7fb8;
                color: white;
            }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>{{ session.session_data.get('tema', 'Sesión sin título') }}</h1>
            <div class="header-meta">
                <div class="meta-item"><strong>Ciclo:</strong> {{ session.session_data.get('ciclo', 'N/A') }}</div>
                <div class="meta-item"><strong>Horas:</strong> {{ session.session_data.get('horasClase', 'N/A') }} h</div>
                <div class="meta-item"><strong>ID Sesión:</strong> {{ session.id }}</div>
            </div>
        </div>

        <div class="section">
            <h2>Contexto</h2>
            <div class="content">{{ session.session_data.get('contexto', '') }}</div>
        </div>

        <div class="section">
            <h2>Competencia a desarrollar</h2>
            <div class="info-box">
                <strong>Competencias seleccionadas:</strong><br/>
                {% for c in session.session_data.get('competenciasSeleccionadas', []) %}
                    • {{ c }}<br/>
                {% endfor %}
            </div>
            <div class="content">{{ session.session_data.get('competenciaDescripcion', '') }}</div>
        </div>

        <div class="section">
            <h2>Materiales y Recursos disponibles</h2>
            <div class="info-box">
                <strong>Materiales:</strong><br/>
                {{ session.session_data.get('materialesDisponibles', 'No especificado') }}
            </div>
            {% if session.session_data.get('materialesDidacticosSugeridos') %}
            <strong style="display: block; margin-top: 10px;">Materiales didácticos sugeridos:</strong>
            <ul>
                {% for m in session.session_data.get('materialesDidacticosSugeridos', []) %}
                    <li>{{ m }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>

        <div class="divider"></div>

        <div class="section">
            <h2>Secuencia Metodológica</h2>
            
            <h3>📌 INICIO (20 minutos)</h3>
            <div class="content">{{ session.session_data.get('secuenciaMetodologica', {}).get('inicio', '') }}</div>
            
            <h3>📌 DESARROLLO (60 minutos)</h3>
            <div class="content">{{ session.session_data.get('secuenciaMetodologica', {}).get('desarrollo', '') }}</div>
            
            <h3>📌 CIERRE (40 minutos)</h3>
            <div class="content">{{ session.session_data.get('secuenciaMetodologica', {}).get('cierre', '') }}</div>
        </div>

        <div class="divider"></div>

        <div class="section">
            <h2>Procesos Didácticos</h2>
            <ul>
                {% for p in session.session_data.get('procesosDidacticos', []) %}
                    <li>{{ p }}</li>
                {% endfor %}
            </ul>
        </div>

        <div class="section">
            <h2>Actividades Contextualizadas</h2>
            <ul>
                {% for a in session.session_data.get('actividadesContextualizadas', []) %}
                    <li>{{ a }}</li>
                {% endfor %}
            </ul>
        </div>

        <div class="section">
            <h2>Distribución de tiempo</h2>
            <div class="info-box">
                {{ session.session_data.get('distribucionHoras', 'No especificado') }}
            </div>
        </div>

        <div class="footer">
            <p>Documento generado automáticamente por EduAI Auth Microservice</p>
            <p style="font-size: 8pt; margin-top: 5px;">Sesión ID: {{ session.id }} | Fecha: {{ session.created_at.strftime('%d/%m/%Y %H:%M') }}</p>
        </div>
    </body>
    </html>
    """)

    html = html_template.render(session=sess)

    # Generate PDF using Playwright (headless browser)
    try:
        pdf_bytes = asyncio.run(_generate_pdf_playwright(html))
    except Exception:
        logger.exception(f"PDF generation failed for session {session_id}")
        raise HTTPException(
            status_code=500,
            detail="PDF generation failed. Ensure Playwright browsers are installed (run: playwright install)."
        )

    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=sesion_{session_id}.pdf"}
    )


async def _generate_pdf_playwright(html_content: str) -> bytes:
    """Generate PDF from HTML using Playwright (Chromium headless browser)."""
    pdf_margin = "0.5in"
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()
        await page.set_content(html_content, wait_until="networkidle")
        pdf_bytes = await page.pdf(
            format="A4",
            margin={"top": pdf_margin, "bottom": pdf_margin, "left": pdf_margin, "right": pdf_margin}
        )
        await browser.close()
        return pdf_bytes
