import os
import logging
import datetime
from fastapi import FastAPI, Depends, HTTPException, status
from fastapi.responses import RedirectResponse
from fastapi.security import OAuth2PasswordRequestForm
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
from dotenv import load_dotenv
from typing import List, Optional, Annotated

load_dotenv()
logger = logging.getLogger(__name__)

from . import models, schemas, auth
from .database import engine, Base, get_db

# create DB tables
Base.metadata.create_all(bind=engine)

app = FastAPI(title="Auth Microservice")


@app.on_event("startup")
def add_sessions_column_if_missing():
    from sqlalchemy import text
    from .database import SessionLocal
    
    db = SessionLocal()
    try:
        bind_engine = db.get_bind()
        dialect_name = bind_engine.dialect.name
        
        logger.info(f"Startup check: database dialect is {dialect_name}")
        
        if dialect_name == "postgresql":
            db.execute(text("ALTER TABLE users ADD COLUMN IF NOT EXISTS sessions JSONB DEFAULT '[]'::jsonb"))
            db.commit()
            logger.info("Successfully checked/added 'sessions' JSONB column to PostgreSQL 'users' table.")
        else:
            try:
                db.execute(text("ALTER TABLE users ADD COLUMN sessions JSON"))
                db.commit()
                logger.info("Successfully added 'sessions' JSON column to SQLite 'users' table.")
            except Exception as e:
                logger.info(f"SQLite check finished (column may already exist): {e}")
    except Exception as e:
        logger.error(f"Error checking/adding sessions column: {e}")
    finally:
        db.close()

# Enable CORS for frontend requests
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Change to specific origins in production: ["https://tu-dominio.com"]
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/", include_in_schema=False)
def root():
    """Root route: redirect to documentation (avoids 404 for GET /)."""
    return RedirectResponse(url="/docs")


@app.post("/register", response_model=schemas.UserOut, responses={400: {"description": "Email already registered"}})
def register(user_in: schemas.UserCreate, db: Annotated[Session, Depends(get_db)]):
    existing = auth.get_user_by_email(db, user_in.email)
    if existing:
        raise HTTPException(status_code=400, detail="Email already registered")
    hashed = auth.get_password_hash(user_in.password)
    user = models.User(email=user_in.email, hashed_password=hashed, full_name=user_in.full_name, provider="email")
    db.add(user)
    db.commit()
    db.refresh(user)
    return user


@app.post("/login", response_model=schemas.Token, responses={401: {"description": "Incorrect email or password"}})
def login(form_data: Annotated[OAuth2PasswordRequestForm, Depends()], db: Annotated[Session, Depends(get_db)]):
    user = auth.authenticate_user(db, form_data.username, form_data.password)
    if not user:
        raise HTTPException(status_code=401, detail="Incorrect email or password")
    access_token = auth.create_access_token({"sub": user.email})
    return {"access_token": access_token, "token_type": "bearer"}


@app.post("/google-login", response_model=schemas.Token, responses={400: {"description": "Google token has no email"}})
def google_login(payload: schemas.GoogleLogin, db: Annotated[Session, Depends(get_db)]):
    # Client should send an id_token obtained from Google Sign-In
    info = auth.verify_google_token(payload.id_token, audience=os.getenv("GOOGLE_CLIENT_ID"))
    email = info.get("email")
    if not email:
        raise HTTPException(status_code=400, detail="Google token has no email")
    user = auth.get_user_by_email(db, email)
    if not user:
        # Create user with provider 'google'
        user = models.User(email=email, full_name=info.get("name"), provider="google")
        db.add(user)
        db.commit()
        db.refresh(user)
    access_token = auth.create_access_token({"sub": user.email})
    return {"access_token": access_token, "token_type": "bearer"}


@app.get("/me", response_model=schemas.UserOut)
def read_me(current_user: Annotated[models.User, Depends(auth.get_current_user)]):
    return current_user


@app.post("/save-session", response_model=schemas.SessionOut, responses={404: {"description": "User not found"}})
def save_session(payload: schemas.SessionCreate, db: Annotated[Session, Depends(get_db)]):
    """Save a session payload generated by the backend or frontend for a user inside the user table."""
    user = auth.get_user_by_email(db, payload.user_id)
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    
    # Initialize sessions list if it is None
    if user.sessions is None:
        user.sessions = []
    
    # We want to support updating an existing session in the list if the session_id matches,
    # or appending a new one if it doesn't.
    new_session_data = payload.session_data
    session_id = str(new_session_data.get("session_id") or new_session_data.get("id") or "")
    if not session_id:
        import time
        session_id = f"session_{int(time.time() * 1000)}"
        new_session_data["session_id"] = session_id
        new_session_data["id"] = session_id
    
    # Ensure created_at / updated_at in session data
    import datetime
    now_str = datetime.datetime.now().isoformat()
    if "created_at" not in new_session_data:
        new_session_data["created_at"] = now_str
    new_session_data["updated_at"] = now_str
    
    # Construct the full session object to store or update in the list
    session_item = {
        "id": session_id,
        "user_id": payload.user_id,
        "session_data": new_session_data,
        "created_at": new_session_data.get("created_at", now_str)
    }
    
    # Update or append in the sessions JSON list
    updated_sessions = []
    found = False
    for s in user.sessions:
        if isinstance(s, dict) and (str(s.get("id")) == session_id or str(s.get("session_data", {}).get("session_id")) == session_id):
            updated_sessions.append(session_item)
            found = True
        else:
            updated_sessions.append(s)
            
    if not found:
        updated_sessions.insert(0, session_item)
        
    # Assign the new list back to flag SQLAlchemy that the JSON column has changed
    from sqlalchemy.orm.attributes import flag_modified
    user.sessions = updated_sessions
    flag_modified(user, "sessions")
    
    db.commit()
    db.refresh(user)
    
    # Return formatted session out
    return {
        "id": session_item["id"],
        "user_id": session_item["user_id"],
        "session_data": session_item["session_data"],
        "created_at": datetime.datetime.fromisoformat(session_item["created_at"])
    }


def _find_session_by_id(db: Session, session_id: str):
    """Finds the user and the session dictionary by session_id in the db."""
    users = db.query(models.User).all()
    for u in users:
        if u.sessions:
            for s in u.sessions:
                if isinstance(s, dict) and (str(s.get("id")) == session_id or str(s.get("session_data", {}).get("session_id")) == session_id):
                    return u, s
    return None, None


def _parse_created_at(created_at_val) -> datetime.datetime:
    """Helper to parse created_at into datetime.datetime."""
    import datetime
    if isinstance(created_at_val, str):
        try:
            return datetime.datetime.fromisoformat(created_at_val)
        except Exception:
            return datetime.datetime.now()
    return datetime.datetime.now()


def _format_session_dict(s: dict, user_email: str) -> dict:
    """Helper to format a session dictionary into SessionOut structure."""
    return {
        "id": str(s.get("id") or s.get("session_data", {}).get("session_id") or "0"),
        "user_id": user_email,
        "session_data": s.get("session_data", s),
        "created_at": _parse_created_at(s.get("created_at"))
    }


def _get_single_user_sessions(user) -> list:
    """Formats sessions for a single user."""
    all_sessions = []
    if user.sessions:
        for s in user.sessions:
            if isinstance(s, dict):
                all_sessions.append(_format_session_dict(s, user.email))
    return all_sessions


def _get_all_users_sessions(db: Session) -> list:
    """Formats all sessions for all users, sorted by created_at descending."""
    all_sessions = []
    users = db.query(models.User).all()
    for u in users:
        if u.sessions:
            for s in u.sessions:
                if isinstance(s, dict):
                    all_sessions.append(_format_session_dict(s, u.email))
    all_sessions.sort(key=lambda x: x["created_at"], reverse=True)
    return all_sessions


@app.get("/sessions", response_model=List[schemas.SessionOut])
def get_sessions(db: Annotated[Session, Depends(get_db)], user_id: Optional[str] = None):
    """List sessions. If user_id is provided, filter by that user_id."""
    if user_id:
        user = auth.get_user_by_email(db, user_id)
        if not user:
            return []
        return _get_single_user_sessions(user)
    else:
        return _get_all_users_sessions(db)


@app.post("/api/sessions/{session_id}/comment", responses={400: {"description": "El comentario no puede estar vacío"}, 404: {"description": "Sesión no encontrada"}})
def add_comment(session_id: str, payload: dict, db: Annotated[Session, Depends(get_db)]):
    """Añade un comentario a una sesión pública guardada en la columna sessions de la tabla users."""
    author = payload.get("author", "Anónimo")
    text = payload.get("text", "")
    
    if not text:
        raise HTTPException(status_code=400, detail="El comentario no puede estar vacío")
        
    user_found, session_item = _find_session_by_id(db, session_id)
    if not user_found or not session_item:
        raise HTTPException(status_code=404, detail="Sesión no encontrada")
        
    session_data = session_item.get("session_data", {})
    comments = session_data.get("comments", [])
    
    import datetime
    now_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    
    new_comment = {
        "id": int(datetime.datetime.now().timestamp() * 1000),
        "author": author,
        "text": text,
        "time": now_str
    }
    
    comments.insert(0, new_comment)
    session_data["comments"] = comments
    session_item["session_data"] = session_data
    
    # Flag SQLAlchemy that the JSON column changed
    from sqlalchemy.orm.attributes import flag_modified
    flag_modified(user_found, "sessions")
    
    db.commit()
    return {"status": "ok", "comment": new_comment}


@app.post("/api/sessions/{session_id}/like", responses={404: {"description": "Sesión no encontrada"}})
def like_session(session_id: str, db: Annotated[Session, Depends(get_db)]):
    """Incrementa los likes de una sesión pública guardada en la columna sessions de la tabla users."""
    user_found, session_item = _find_session_by_id(db, session_id)
    if not user_found or not session_item:
        raise HTTPException(status_code=404, detail="Sesión no encontrada")
        
    session_data = session_item.get("session_data", {})
    likes = session_data.get("likes", 0) + 1
    session_data["likes"] = likes
    session_item["session_data"] = session_data
    
    # Flag SQLAlchemy that the JSON column changed
    from sqlalchemy.orm.attributes import flag_modified
    flag_modified(user_found, "sessions")
    
    db.commit()
    return {"status": "ok", "likes": likes}

